import { Code2 } from "lucide-react";

import { Card } from "@/components/ui/card";

type GeneratedSqlCardProps = {
  sql?: string;
};

export function GeneratedSqlCard({ sql }: GeneratedSqlCardProps) {
  return (
    <Card className="p-5">
      <div className="mb-4 flex items-center gap-3">
        <span className="grid size-10 place-items-center rounded-xl border border-primary/30 bg-primary/10 text-primary">
          <Code2 className="size-5" />
        </span>
        <div>
          <h2 className="text-sm font-semibold text-white">Generated SQL</h2>
          <p className="text-xs text-slate-500">Generated by SemanticSQL.</p>
        </div>
      </div>

      <pre className="overflow-x-auto rounded-xl border border-white/[0.08] bg-slate-950/70 p-5 font-mono text-sm leading-7 text-cyan-100">
        <code>{sql?.trim() ? sql : "Generate a query to see SQL here."}</code>
      </pre>
    </Card>
  );
}
